resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Docker
  steps:
  - checkout: self
    clean: true
  - task: Bash@3
    displayName: Maven build
    inputs:
      targetType: inline
      script: "# Write your commands here\n\nls -ltra \n./mvnw clean install -DskipTests\n"
  - task: Docker@2
    displayName: buildAndPush
    inputs:
      containerRegistry: b801bd78-db35-41f8-938a-bec3b498bfc8
      repository: springboot-petclinic-actions
      tags: v1
  - task: Docker@2
    displayName: Logout of Docker Regsitry
    inputs:
      command: logout
      containerRegistry: b801bd78-db35-41f8-938a-bec3b498bfc8
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact'
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)'
      artifact: artifact

