apiVersion : apps/v1
kind: Deployment
metadata:
  name: "productzero-2d34"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "productzero-2d34"
  template:
    metadata:
      labels:
        app: "productzero-2d34"
    spec:
      containers:
        - name: "productzero-2d34"
          image: "productzero.azurecr.io/productzero"
          ports:
          - containerPort: 80
          readinessProbe:
          initialDelaySeconds: 1200
          timeoutSeconds: 1200
