apiVersion: v1
kind: Service
metadata:
    name: "productzero-2d34"
    labels:
        app: "productzero-2d34"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "productzero-2d34"