on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: productzero.azurecr.io
        username: ${{ secrets.acr_productzero_username }}
        password: ${{ secrets.acr_productzero_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "dockerfile" -t productzero.azurecr.io/productzero:${{ github.sha }} --label dockerfile-path=dockerfile
        docker push productzero.azurecr.io/productzero:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_productzero_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep product-zero9f60 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace product-zero9f60`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: product-zero9f60
        container-registry-url: productzero.azurecr.io
        container-registry-username: ${{ secrets.acr_productzero_username }}
        container-registry-password: ${{ secrets.acr_productzero_password }}
        secret-name: productzerodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: product-zero9f60
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          productzero.azurecr.io/productzero:${{ github.sha }}
        imagepullsecrets: |
          productzerodockerauth
